FROM python:3.10
WORKDIR /app
COPY watcher-agent.py .
#RUN pip install requests time datatime cx_Oracle==8.3.0
RUN pip install cx_Oracle==8.3.0 requests==
RUN cd /opt/ && mkdir /opt/oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/214000/instantclient-basic-linux.x64-21.4.0.0.0dbru.zip
RUN unzip instantclient_21_4 && \ 
    apt update && apt install libaio1 && \
    sh -c "echo /opt/oracle/instantclient_21_4 > /etc/ld.so.conf.d/oracle-instantclient.conf" && \
    ldconfig
CMD ["python","watcher-agent.py"]

